USE DATAMARKET;


CREATE TABLE PDVS (
    ID_PDV INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_PDV CHAR(2) NOT NULL, 
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(50)
);


CREATE TABLE FORNECEDORES(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(11),
    EMAIL VARCHAR(100),
    ENDERECO TEXT,
    SEGMENTO VARCHAR(40)
);


CREATE TABLE PRODUTOS(
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA_ID INT NOT NULL,
    FORNECEDOR_ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    PRECO_VENDA DECIMAL(10,2) NOT NULL,
    PRECO_CUSTO DECIMAL(10,2) NOT NULL,
    UNIDADE VARCHAR(15) NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);


CREATE TABLE ESTOQUE(
    ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID INT NOT NULL,
    QTD_DISPONIVEL INT NOT NULL,
    FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTOS(ID_PRODUTO)
);


CREATE TABLE CLIENTES (
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);


CREATE TABLE FUNCIONARIOS (
	MATRICULA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CARGO VARCHAR(20) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	ATIVO BOOLEAN NOT NULL
);


CREATE TABLE GASTOS_FUNCIONARIOS (
	ID_GASTO INT PRIMARY KEY AUTO_INCREMENT,
	FUNCIONARIO_ID INT NOT NULL,
	TIPO_GASTO VARCHAR(30) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA DATE NOT NULL,
	FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(MATRICULA)
);


CREATE TABLE OUTRAS_DESPESAS (
	ID_GASTO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_GASTO VARCHAR(30) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	DATA DATE NOT NULL,
	DESCRICAO TEXT NOT NULL
);


CREATE TABLE TIPOS_PAGAMENTO (
	ID_TIPO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(30) NOT NULL
);


CREATE TABLE CUPONS (
	ID_CUPOM INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(20) UNIQUE NOT NULL,
	DESCRICAO TEXT,
	PERCENTUAL_DESCONTO DECIMAL(5,2),
	VALIDADE DATE,
	ATIVO BOOLEAN NOT NULL
);


CREATE TABLE VENDAS (
	ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_VENDA DATE NOT NULL,
	PDV_ID INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	FUNCIONARIO_ID INT NOT NULL,
	TIPO_PAGAMENTO_ID INT NOT NULL,
	CUPOM_ID INT,
	VALOR_TOTAL DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (PDV_ID) REFERENCES PDVS(ID_PDV),
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE),
	FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(MATRICULA),
	FOREIGN KEY (TIPO_PAGAMENTO_ID) REFERENCES TIPOS_PAGAMENTO(ID_TIPO),
	FOREIGN KEY (CUPOM_ID) REFERENCES CUPONS(ID_CUPOM)
);

CREATE TABLE ITENS_VENDA (
	ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
	VENDA_ID INT NOT NULL,
	PRODUTO_ID INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(ID_VENDA),
	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE NOTAS_FISCAIS (
	ID_NOTA INT PRIMARY KEY AUTO_INCREMENT,
	VENDA_ID INT NOT NULL,
	NUMERO_NOTA VARCHAR(20) UNIQUE NOT NULL,
	CHAVE_ACESSO CHAR(44) UNIQUE NOT NULL,
	DATA_EMISSAO DATE NOT NULL,
	FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(ID_VENDA)
);


CREATE TABLE MOVIMENTACAO_ESTOQUE (
	ID_MOV INT PRIMARY KEY AUTO_INCREMENT,
	PRODUTO_ID INT NOT NULL,
	TIPO_MOVIMENTACAO ENUM('ENTRADA', 'SAIDA') NOT NULL,
	QUANTIDADE INT NOT NULL,
	DATA DATE NOT NULL,
	ORIGEM VARCHAR(100),
	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(ID_PRODUTO)
);


