CREATE DATABASE CLINICA;

USE CLINICA;

CREATE TABLE ENDERECO(
ID_ENDERECO int primary key auto_increment,
CIDADE varchar(30) NOT NULL,
UF char(2) NOT NULL,
RUA varchar(50) NOT NULL,
BAIRRO varchar(30) NOT NULL
);

CREATE TABLE MEDICOS(
ID_MEDICO INT PRIMARY KEY auto_increment,
NOME VARCHAR(40) NOT NULL,
SOBRENOME VARCHAR(30) NOT NULL,
ESPECIALIDADE VARCHAR(30) NOT NULL,
CRM VARCHAR(11) NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL,
SALARIO DECIMAL(10,2) NOT NULL,
ID_ENDERECO INT NOT NULL,
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);


CREATE TABLE PACIENTES(
ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(40) NOT NULL,
SOBRENOME VARCHAR(40) NOT NULL,
CPF VARCHAR(11) NOT NULL,
DATA_NASC DATE,
SEXO CHAR(1) NOT NULL,
TELEFONE VARCHAR(12) NOT NULL,
EMAIL VARCHAR(50),
DATA_CADASTRO DATE,
ID_ENDERECO INT,
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE CONSULTAS(
ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT, 
ID_PACIENTE INT NOT NULL,
ID_MEDICO INT NOT NULL,
DATA_CONSULLTA DATE,
VALOR DECIMAL(10,2) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
TIPO_PAGAMENTO VARCHAR(16) NOT NULL,
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);


CREATE TABLE CATEGORIA_GASTOS(
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR(30)
);

CREATE TABLE GASTOS(
ID_GASTO INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(40) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DATA DATE NOT NULL,
ID_CATEGORIA INT
);


CREATE TABLE SATISFACAO_CLIENTES(
ID_AVALIACAO INT PRIMARY KEY AUTO_INCREMENT,
ID_CONSULTA INT NOT NULL,
NOTA INT NOT NULL,
COMENTARIO TEXT,
DATA_AVALIACAO DATE,
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTAS(ID_CONSULTA)
);


CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
SOBRENOME VARCHAR(30) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
SALARIO DECIMAL(10,2),
DATA_ADMISSAO DATE,
STATUS VARCHAR(20)
);

CREATE TABLE SATISFACAO_FUNCIONARIOS(
ID_AVALIACAO INT PRIMARY KEY AUTO_INCREMENT,
ID_FUNCIONARIO INT,
NOTA INT NOT NULL,
COMENTARIO TEXT,
DATA_AVALIACAO DATE,
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);


CREATE TABLE PRESCRICOES(
 ID_PRESCRICAO INT PRIMARY KEY AUTO_INCREMENT,
 ID_CONSULTA INT,
 MEDICAMENTO VARCHAR(30),
 DOSAGEM VARCHAR(20),
 FREQUENCIA VARCHAR(20),
 DURACAO_DIAS INT,
 FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTAS(ID_CONSULTA)
);