-- QUANTOS $ ESTAMOS GASTANDO COM SALÁRIO DE FUNCIONÁRIOS
SELECT SUM(SALARIO) AS GASTO_SALARIOS_FUNCIONARIOS
FROM FUNCIONARIOS;

-- QUANTOS $ ESTAMOS GASTANDO COM SALÁRIOS DE MÉDICOS - R$ 85000.00
SELECT SUM(SALARIO) AS GASTO_SALARIOS_MEDICOS
FROM MEDICOS;

-- QUANTOS $ ESTAMOS GASTANDO MENSALMENTE COM TODOS OS SALARIOS - R$ 170600.00
SELECT 
(SELECT SUM(SALARIO) FROM funcionarios) +
(SELECT SUM(SALARIO) FROM medicos AS GASTO_TOTAL_SALARIOS)

-- Gastos gerais  - R$ 101500.00
SELECT SUM(VALOR) AS VALOR_DESPESAS
FROM gastos

-- TOTAL GASTO -  > R$ 272100.00
SELECT 
(SELECT SUM(SALARIO) FROM funcionarios) +
(SELECT SUM(SALARIO) FROM medicos) + 
(SELECT SUM(VALOR) FROM gastos AS VALOR_GASTO_MARÇO)

-- LUCRO TOTAL -> R$ 6480.00
SELECT SUM(VALOR) AS TOTAL_LUCRO 
FROM CONSULTAS ;



